# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmTOFSfUAxRxIMy-yKLrV8v4RaXcFS0m
"""

import streamlit as st
import pandas as pd
import shap
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, confusion_matrix, auc, classification_report
from pytorch_tabnet.tab_model import TabNetClassifier
import torch
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# ========== PAGE CONFIGURATION ==========
st.set_page_config(
    page_title="Ubi 'Kinampay' Variety ID and Geographic Origin Confirmation",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ========== HEADER ==========
st.markdown("""
    <h1 style='text-align: center; color: purple;'>
        Ubi 'Kinampay' Variety Identification & Origin Confirmation
    </h1>
    <h4 style='text-align: center; color: gray;'>
        Powered by TabNet + PCA + SHAP
    </h4>
""", unsafe_allow_html=True)

# ========== LOAD DATA ==========
st.sidebar.header("📂 Upload Files")
pca_file = st.sidebar.file_uploader("Upload PCA Scores CSV", type=["csv"])
y_file = st.sidebar.file_uploader("Upload Target Variable CSV", type=["csv"])

if pca_file and y_file:
    x_pca = pd.read_csv(pca_file)
    y = pd.read_csv(y_file)["Class"]

    # Select PC1 and PC2
    pc_cols = [col for col in x_pca.columns if col in ["PC1", "PC2"]]
    x_pca = x_pca[pc_cols]

    # Apply SMOTE
    X_resampled, y_resampled = SMOTE(random_state=42).fit_resample(x_pca.values, y)
    X_train, X_test, y_train, y_test = train_test_split(
        X_resampled, y_resampled, test_size=0.2, random_state=42
    )

    # ========== TRAIN MODEL ==========
    clf = TabNetClassifier(
        n_d=16, n_a=16, n_steps=5, gamma=1.5, lambda_sparse=1e-4,
        optimizer_fn=torch.optim.Adam, optimizer_params=dict(lr=1e-3),
        scheduler_fn=torch.optim.lr_scheduler.StepLR,
        scheduler_params={"step_size": 10, "gamma": 0.9},
        mask_type='entmax', verbose=0, seed=42
    )

    clf.fit(
        X_train=X_train, y_train=y_train,
        eval_set=[(X_test, y_test)],
        max_epochs=150, patience=20,
        batch_size=32, virtual_batch_size=16
    )

    y_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]

    # ========== METRICS SECTION ==========
    st.markdown("""
    <h2 style='color: purple;'>📊 Model Evaluation Metrics</h2>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Confusion Matrix")
        cm = confusion_matrix(y_test, y_pred)
        fig, ax = plt.subplots()
        sns.heatmap(cm, annot=True, fmt="d", cmap="Purples", cbar=False, ax=ax)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        st.pyplot(fig)

    with col2:
        st.subheader("ROC Curve")
        fpr, tpr, _ = roc_curve(y_test, y_prob)
        roc_auc = auc(fpr, tpr)
        fig2, ax2 = plt.subplots()
        ax2.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}", color="purple")
        ax2.plot([0, 1], [0, 1], linestyle="--", color="gray")
        ax2.set_xlabel("False Positive Rate")
        ax2.set_ylabel("True Positive Rate")
        ax2.set_title("ROC Curve")
        ax2.legend()
        st.pyplot(fig2)

    # ========== SHAP PLOTS ==========
    st.markdown("""
    <h2 style='color: purple;'>🔍 SHAP Model Explainability</h2>
    """, unsafe_allow_html=True)

    with st.spinner("Calculating SHAP values..."):
        explainer = shap.Explainer(clf.predict, X_train)
        shap_values = explainer(X_test)

    with st.expander("🔎 SHAP Summary Plot"):
        fig3 = plt.figure()
        shap.summary_plot(shap_values.values, X_test, feature_names=pc_cols, show=False)
        st.pyplot(fig3)

    with st.expander("📌 Feature Importance Bar Chart"):
        fig4, ax4 = plt.subplots()
        importances = clf.feature_importances_
        sns.barplot(x=importances, y=pc_cols, palette="Purples_r", ax=ax4)
        ax4.set_title("TabNet Feature Importance")
        st.pyplot(fig4)

else:
    st.info("👈 Upload the required CSV files to get started.")